---
# tasks file for common

# Copyright (C) 2019 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: upgrade all packages
  become: yes
  yum:
    name: "*"
    exclude: docker-ce
    state: latest
  retries: 60
  delay: 5
  register: result
  until: result is succeeded
  tags:
    - common

- name: install epel-release
  become: yes
  yum: 
    name: epel-release
    state: latest 
  retries: 60
  delay: 5
  register: result
  until: result is succeeded
  tags:
    - common

- name: ensure development related packages are installed
  become: yes
  yum: 
    name: 
      - sudo
      - unzip
      - wget
      - lynx
      - nano
      - vim
      - emacs
      - bind-utils
      - bash-completion 
      - bash-completion-extras
  retries: 60
  delay: 5
  register: result
  until: result is succeeded
  tags:
    - common

- name: ensure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: yes
  tags:
    - common

- name: configure 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  tags:
    - common

- name: ensure {{ ansible_user_id  }} is added to wheel group
  become: yes
  user: 
    name: "{{ ansible_user_id  }}"
    groups: wheel 
    append: yes 
    state: present 
  tags:
    - common

- name: ensure /usr/local/bin is included in everyone's PATH env
  become: yes
  copy:
    dest: /etc/profile.d/usr_local_bin.sh
    content: |
      pathmunge /usr/local/bin
    mode: '0644' 
   
- name: ensure sudo can run /usr/local/bin files
  become: yes  
  lineinfile:
   path: /etc/sudoers
   regexp: '^Defaults    secure_path ='
   line: Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
