---
# tasks file for docker
# Based on https://docs.docker.com/install/linux/docker-ce/centos/

# Copyright (C) 2019 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: uninstall old versions of docker
  become: yes
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent
  tags:
    - docker

- name: ensure docker group exists
  become: yes
  group:
    name: docker
    state: present
  tags:
    - docker

- name: ensure Docker CE repository is added
  become: yes
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  tags:
    - docker

- name: ensure the latest version of Docker CE is installed
  become: yes
  yum:
    state: latest
    name: docker-ce
  retries: 60
  delay: 5
  register: result
  until: result is succeeded
  tags:
    - docker

- name: vagrant proxy plugin expects /etc/systemd/system/docker.service.d/http-proxy.conf to exist
  block:
  - name: Create /etc/systemd/system/docker.service.d/
    become: yes
    file:
      path: /etc/systemd/system/docker.service.d/
      state: directory

  - name: ensure /etc/systemd/system/docker.service.d/http-proxy.conf
    become: yes
    file:
      path: /etc/systemd/system/docker.service.d/http-proxy.conf
      state: touch
  tags:
    - docker

- name: ensure docker service is enabled
  become: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker

- name: template in /etc/sysconfig/docker
  become: true
  template:
    src: templates/etc/sysconfig/docker.j2
    dest: /etc/sysconfig/docker
    force: yes
  register: sysconfigDocker
  tags:
    - docker

- name: debug
  become: true
  command: /bin/bash -c "cat /etc/sysconfig/docker"
  when: sysconfigDocker.changed
  tags:
    - docker

- name: configured Docker options (e.g., insecure registry, DNS)
  become: yes
  template:
    src: templates/etc/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
    force: yes
  register: daemon
  tags:
    - docker

- name: debug
  become: yes
  command: /bin/bash -c "cat /etc/docker/daemon.json"
  when: daemon.changed
  tags:
    - docker

- name: configure EnvironmentFile
  become: yes
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/docker.service
    insertafter: "^\\[Service\\]"
    regexp: "^aEnvironmentFile="
    line: "EnvironmentFile=/etc/sysconfig/docker"
  register: environmentFile
  tags:
    - docker

- name: stop and reload docker service
  block:
  - name: stop docker service
    service:
      name: docker
      enabled: yes
      state: stopped
  - name: reload docker service
    systemd:
      name: docker
      daemon_reload: yes
  become: yes
  when: daemon.changed
  tags:
    - docker

- name: start and enable docker service
  become: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker

- name: debug
  command: /bin/bash -c "systemctl is-active docker"
  tags:
    - docker

- name: "add {{ ansible_user_id }} user to docker group"
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - docker
